# Generated by Django 5.1.8 on 2026-05-31 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_customuser_best_overall_streak_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='google_calendar_integration',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='morning_lark_streak',
        ),
    ]
